name: Update Recent Activity

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Readme-Workflows/recent-activity@v2.0.0
        with:
          GH_USERNAME: sxrxvxnn
          CONFIG_FILE: ./.github/recent-activity.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
